name: daily job

on:
  push:
    branches:
      - main
  schedule:
    - cron: '59 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
      - run: conda --version
      - run: which python
      - run: python -m pip install --upgrade pip
      - run: conda install -c conda-forge ta-lib 
      - run: pip install .