name: daily job

on:
  schedule:
    - cron: '59 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
      - run: conda --version
      - run: which python
      - run: python -m pip install --upgrade pip
      - run: conda install -c conda-forge ta-lib
      - run: pip install .
      - name: run daily job
        run: python week_job.py
      - name: Commit files
        run: |
          git init
          git config --local user.name Lisa06010416
          git config --local user.email lisalin0601@gmail.com
          git status
          git remote add origin https://github.com/Lisa06010416/FinancialIndicators.git
          git add --all
          git commit -m "update data ..."
          git push origin main -f